# Generated by Django 5.0.2 on 2025-03-12 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='config_apil_timesta_e7c655_idx'), models.Index(fields=['path'], name='config_apil_path_2a61e5_idx'), models.Index(fields=['method'], name='config_apil_method_de24b5_idx'), models.Index(fields=['status_code'], name='config_apil_status__63e361_idx')],
            },
        ),
    ]
