# Generated by Django 5.0.2 on 2025-03-12 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='frontend_timestamp',
            field=models.DateTimeField(blank=True, help_text='Client-side timestamp', null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='log_type',
            field=models.CharField(choices=[('api', 'API Call'), ('page', 'Page View')], default='api', max_length=10),
        ),
        migrations.AddField(
            model_name='apilog',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['log_type'], name='config_apil_log_typ_ec451f_idx'),
        ),
    ]
