# version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - shared_network
    ports:
      - "3010:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8010/api
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - shared_network
    volumes:
      - ./backend:/app
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/webapp2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webapp2
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    networks:
      - shared_network
    environment:
      POSTGRES_DB: webapp2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 

networks:
  shared_network:
    external: true