# Generated by Django 5.0.2 on 2025-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_table_link',
            field=models.URLField(blank=True, help_text="URL to the league's standings/table", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='team_link',
            field=models.URLField(blank=True, help_text="URL to the team's website or page", max_length=500, null=True),
        ),
    ]
