# Generated by Django 5.0.2 on 2025-03-10 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_league_table_link_league_team_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_first_name', models.CharField(max_length=100)),
                ('roster_last_name', models.CharField(max_length=100)),
                ('roster_full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_mappings', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roster_full_name'],
                'unique_together': {('league', 'roster_first_name', 'roster_last_name')},
            },
        ),
    ]
