# Generated by Django 5.0.2 on 2025-04-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_playernamemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('venue', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('fixture_date', models.DateField()),
                ('for_score', models.IntegerField(blank=True, null=True)),
                ('against_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='leagues.league')),
            ],
            options={
                'ordering': ['fixture_date'],
                'unique_together': {('league', 'opponent', 'fixture_date')},
            },
        ),
    ]
