# Generated by Django 5.2 on 2025-04-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_fixture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('prefer_not', 'Prefer Not')], default='available', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about availability', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_availabilities', to='leagues.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Player availabilities',
                'unique_together': {('fixture', 'player')},
            },
        ),
    ]
