# Generated by Django 5.0.2 on 2025-03-06 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_alter_competition_status_gamescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_bowls', to='users.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_social_bowls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Bowl',
                'verbose_name_plural': 'Social Bowls',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SocialBowlParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('social_bowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='social.socialbowl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_bowl_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Bowl Participant',
                'verbose_name_plural': 'Social Bowl Participants',
                'unique_together': {('social_bowl', 'user')},
            },
        ),
    ]
