# Generated by Django 5.0.2 on 2025-03-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_add_notice_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialbowlparticipant',
            options={'verbose_name': 'Notice Participant', 'verbose_name_plural': 'Notice Participants'},
        ),
    ]
