# Generated by Django 5.0.2 on 2025-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_socialbowlparticipant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbowl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/images/'),
        ),
        migrations.AddField(
            model_name='socialbowl',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/pdfs/'),
        ),
    ]
