# Generated by Django 5.0.2 on 2025-03-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_socialbowl_image_socialbowl_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notices/images/additional/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='social.socialbowl')),
            ],
            options={
                'verbose_name': 'Notice Image',
                'verbose_name_plural': 'Notice Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
