# Generated by Django 5.0.2 on 2025-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_noticeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbowl',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
