# Generated by Django 5.0.2 on 2025-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialbowl_is_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialbowl',
            name='notice_type',
            field=models.CharField(choices=[('social_bowl', 'Social Bowling'), ('general', 'General Notice'), ('for_sale', 'For Sale'), ('broadcast', 'Broadcast Notice')], default='social_bowl', max_length=20),
        ),
    ]
