# Generated by Django 5.0.2 on 2025-03-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        # This migration ensures the tables created in 0001_initial are properly
        # recognized in the database. It's a fix for the "relation does not exist" error.
    ]
