# Generated by Django 5.0.2 on 2025-03-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
