# Generated by Django 5.0.2 on 2025-03-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_add_archived_field'),
        ('social', '0005_noticeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_chats', to='social.socialbowl'),
        ),
    ]
