# Generated by Django 5.0.2 on 2025-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_competitionuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionuser',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='competitionuser',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
