# Generated by Django 5.0.2 on 2025-02-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_competition_name'),
        ('users', '0003_alter_competitionuser_options_competitionuser_order'),
    ]

    operations = [
    ]
