# Generated by Django 5.0.2 on 2025-02-23 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250223_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.competition')),
                ('side_1_player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_1_games', to='users.competitionuser')),
                ('side_1_player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_2_games', to='users.competitionuser')),
                ('side_1_player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_3_games', to='users.competitionuser')),
                ('side_1_player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_4_games', to='users.competitionuser')),
                ('side_2_player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_1_games', to='users.competitionuser')),
                ('side_2_player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_2_games', to='users.competitionuser')),
                ('side_2_player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_3_games', to='users.competitionuser')),
                ('side_2_player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_4_games', to='users.competitionuser')),
            ],
            options={
                'ordering': ['round', 'created_at'],
                'unique_together': {('competition', 'round')},
            },
        ),
    ]
