# Generated by Django 5.0.2 on 2025-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_competitionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('scheduled', 'Scheduled')], default='open', max_length=20),
        ),
    ]
