# Generated by Django 5.0.2 on 2025-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_competition_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionschedule',
            options={'ordering': ['round', 'sub_round', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='competitionschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='sub_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='competitionschedule',
            unique_together={('competition', 'round', 'sub_round')},
        ),
    ]
