# Generated by Django 5.0.2 on 2025-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_competitionschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='parallel_matches',
            field=models.IntegerField(default=1),
        ),
    ]
