# Generated by Django 5.0.2 on 2025-02-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_competition_parallel_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_1_player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_1_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_1_player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_2_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_1_player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_3_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_1_player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_1_player_4_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_2_player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_1_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_2_player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_2_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_2_player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_3_games', to='users.competitionuser'),
        ),
        migrations.AlterField(
            model_name='competitionschedule',
            name='side_2_player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_2_player_4_games', to='users.competitionuser'),
        ),
    ]
