# Generated by Django 5.0.2 on 2025-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_competitionschedule_side_1_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_rounds',
            field=models.IntegerField(default=5),
        ),
    ]
