# Generated by Django 5.0.2 on 2025-03-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='club_role',
            field=models.CharField(blank=True, choices=[('', 'No Role'), ('President', 'President'), ('Vice-President', 'Vice-President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary')], default='', max_length=20),
        ),
    ]
