# Generated by Django 5.0.2 on 2025-03-16 16:40

from django.db import migrations


def create_competition_types(apps, schema_editor):
    CompetitionType = apps.get_model('users', 'CompetitionType')
    
    # Create the initial competition types
    CompetitionType.objects.create(id=1, name="Round Robin", description="Players compete against each other in a round-robin format")
    CompetitionType.objects.create(id=2, name="Knockout", description="Single or double elimination tournament format")
    CompetitionType.objects.create(id=3, name="Groups then Finals", description="Players compete in groups, then top performers advance to finals")


def reverse_competition_types(apps, schema_editor):
    CompetitionType = apps.get_model('users', 'CompetitionType')
    CompetitionType.objects.filter(id__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_create_competition_type'),
    ]

    operations = [
        migrations.RunPython(create_competition_types, reverse_competition_types),
    ]
