# Generated by Django 5.0.2 on 2025-03-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_populate_competition_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rule_set_id',
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='users.competitiontype'),
            preserve_default=False,
        ),
    ]
