# Generated by Django 5.0.2 on 2025-03-16 16:42

from django.db import migrations


def update_competition_types(apps, schema_editor):
    # Note: Since rule_set_id has already been removed from the model in the previous migration,
    # we can't directly access it. This migration is primarily to properly display this migration for documentation purposes.
    # The default value of 1 (Round Robin) was already set for all existing competitions in the previous migration.
    
    # If you need to set specific types for certain competitions, you could do it by competition ID, for example:
    Competition = apps.get_model('users', 'Competition')
    CompetitionType = apps.get_model('users', 'CompetitionType')
    
    # Get the competition types
    round_robin = CompetitionType.objects.get(id=1)  # Round Robin
    knockout = CompetitionType.objects.get(id=2)     # Knockout
    groups_finals = CompetitionType.objects.get(id=3)  # Groups then Finals
    
    # Optionally update specific competitions if needed
    # Competition.objects.filter(id=SOME_ID).update(competition_type=knockout)
    # Competition.objects.filter(id=ANOTHER_ID).update(competition_type=groups_finals)


def reverse_update(apps, schema_editor):
    # Nothing to do here since we can't go back to rule_set_id
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_update_competition_model'),
    ]

    operations = [
        migrations.RunPython(update_competition_types, reverse_update),
    ]
